
import contato.Agenda;
import contato.Contato;
import contato.TipoContato;
import javax.swing.table.DefaultTableModel;
import pessoa.Pessoa;
import pessoa.PessoaFisica;
import pessoa.PessoaJuridica;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Pichau
 */
public class Principal extends javax.swing.JFrame {

    Agenda agenda = new Agenda();

    public Principal() {
        
        initComponents();
        carregaCb();
        desabilita();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        lbSobrenome = new javax.swing.JLabel();
        btValidar = new javax.swing.JButton();
        lbCodigo = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lbTelefone = new javax.swing.JLabel();
        txtContato = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        lbContato = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPessoa = new javax.swing.JTable();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        rdFisica = new javax.swing.JRadioButton();
        rdJuridica = new javax.swing.JRadioButton();
        lbConflito = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });

        lbNome.setText("Nome");

        lbSobrenome.setText("Sobrenome");

        btValidar.setText("Validar código");
        btValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValidarActionPerformed(evt);
            }
        });

        lbCodigo.setText("Código");

        txtSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSobrenomeActionPerformed(evt);
            }
        });

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lbTelefone.setText("Telefone");

        txtContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContatoActionPerformed(evt);
            }
        });

        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });

        lbContato.setText("Contato");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        tbPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sobrenome", "Código", "Tipo", "Telefone", "Contato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPessoaMouseClicked(evt);
            }
        });
        tbPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbPessoaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbPessoa);
        if (tbPessoa.getColumnModel().getColumnCount() > 0) {
            tbPessoa.getColumnModel().getColumn(0).setResizable(false);
            tbPessoa.getColumnModel().getColumn(1).setResizable(false);
            tbPessoa.getColumnModel().getColumn(2).setResizable(false);
            tbPessoa.getColumnModel().getColumn(3).setResizable(false);
            tbPessoa.getColumnModel().getColumn(4).setResizable(false);
            tbPessoa.getColumnModel().getColumn(5).setResizable(false);
        }

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        rdFisica.setText("Física");
        rdFisica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdFisicaMouseClicked(evt);
            }
        });

        rdJuridica.setText("Jurídica");
        rdJuridica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdJuridicaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbSobrenome)
                                        .addGap(16, 16, 16)
                                        .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbContato, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbTelefone)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbConflito, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btSalvar)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(150, 150, 150)
                                            .addComponent(btExcluir))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(80, 80, 80)
                                            .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(83, 83, 83)
                                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lbCodigo)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rdFisica)
                                        .addGap(0, 0, 0)
                                        .addComponent(rdJuridica))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbNome)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbContato)
                                    .addComponent(lbCodigo))))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSobrenome)
                            .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbTelefone))
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbConflito, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSalvar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btExcluir)
                                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btValidar))
                            .addComponent(btNovo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdFisica)
                            .addComponent(rdJuridica))))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void txtSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSobrenomeActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContatoActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        txtCod.setText("");
        txtContato.setText("");
        txtNome.setText("");
        txtSobrenome.setText("");
        txtTelefone.setText("");
        rdFisica.setSelected(false);
        rdJuridica.setSelected(false);
        limpaLbConflito();
        desabilita();
        rdFisica.setEnabled(true);
        rdJuridica.setEnabled(true);
        lbCodigo.setText("Código");

    }//GEN-LAST:event_btNovoActionPerformed

    private void desabilita() {
        btExcluir.setEnabled(false);
        btSalvar.setEnabled(false);
        txtContato.setEnabled(false);
        txtTelefone.setEnabled(false);
        cbTipo.setEnabled(false);
    }

    private void habilita() {
        btExcluir.setEnabled(true);
        btSalvar.setEnabled(true);
        txtContato.setEnabled(true);
        txtTelefone.setEnabled(true);
        cbTipo.setEnabled(true);
    }

    private void limpaLbConflito() {
        lbConflito.setText("");
    }

    private void btValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValidarActionPerformed
        limpaLbConflito();
        if (rdFisica.isSelected() && rdJuridica.isSelected()) {
            lbConflito.setText("Selecionar apenas uma opção!");
            desabilita();
        } else {
            if (rdFisica.isSelected()) {
                if (txtCod.getText().length() == 11) {
                    habilita();
                    limpaLbConflito();
                } else {
                    lbConflito.setText("CPF inválido");
                    desabilita();
                }
            } else {
                if (txtCod.getText().length() == 14) {
                    habilita();
                    limpaLbConflito();
                } else {
                    lbConflito.setText("CNPJ inválido");
                    desabilita();
                }
            }
        }
        if (!rdFisica.isSelected() && !rdJuridica.isSelected()) {
            lbConflito.setText("Selecionar uma opção!");
            desabilita();
        }
    }//GEN-LAST:event_btValidarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        if (rdFisica.isSelected() && rdJuridica.isSelected()) {
            lbConflito.setText("Selecionar apenas uma opção");
        } else {
            if (txtNome.getText().isEmpty() || txtContato.getText().isEmpty() || txtCod.getText().isEmpty() || txtTelefone.getText().isEmpty()) {
                lbConflito.setText("Completar cadastro");
            } else {
                String nome, sobrenome, codigo, telefone, contato;
                telefone = txtTelefone.getText();
                contato = txtContato.getText();
                TipoContato tipo = null;
                int indexTipo = cbTipo.getSelectedIndex();
                switch (indexTipo) {
                    case 0:
                        tipo = TipoContato.EMAIL;
                        break;

                    case 1:
                        tipo = TipoContato.FAX;
                        break;

                    case 2:
                        tipo = TipoContato.SINAL_FUMACA;
                        break;

                    case 3:
                        tipo = TipoContato.WHATSAPP;
                }
                Contato cont = new Contato(contato, tipo, telefone);
                sobrenome = txtSobrenome.getText();
                nome = txtNome.getText();
                codigo = txtCod.getText();
                if (rdFisica.isSelected()) {
                    PessoaFisica pessoa = new PessoaFisica(nome, sobrenome, codigo);
                    pessoa.setContato(cont);
                    agenda.addPessoa(pessoa);
                } else {
                    PessoaJuridica pessoa = new PessoaJuridica(nome, sobrenome, codigo);
                    pessoa.setContato(cont);
                    agenda.addPessoa(pessoa);
                }
                DefaultTableModel dtb = (DefaultTableModel) tbPessoa.getModel();
                Object[] pessoas = {txtNome.getText(), txtSobrenome.getText(), txtCod.getText(), cbTipo.getSelectedItem(), txtTelefone.getText(), txtContato.getText()};
                dtb.addRow(pessoas);
                btNovoActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (tbPessoa.getSelectedRow() != -1) {
            for (int i = 0; i > agenda.getPessoas().size(); i++) {
                if (agenda.getPessoas().get(i) instanceof PessoaFisica) {
                    PessoaFisica pessoa = (PessoaFisica) agenda.getPessoas().get(i);
                    if (pessoa.getCpf().equals((String) tbPessoa.getValueAt(tbPessoa.getSelectedRow(), 2))) {
                        agenda.removePessoa(pessoa);
                    }
                } else {
                    PessoaJuridica pessoa = (PessoaJuridica) agenda.getPessoas().get(i);
                    if (pessoa.getCnpj().equals((String) tbPessoa.getValueAt(tbPessoa.getSelectedRow(), 2))) {
                        agenda.removePessoa(pessoa);
                    }
                }
            }
            DefaultTableModel dtb = (DefaultTableModel) tbPessoa.getModel();
            dtb.removeRow(tbPessoa.getSelectedRow());
            btNovoActionPerformed(evt);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void tbPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPessoaMouseClicked
        if (tbPessoa.getSelectedRow() != -1) {
            txtNome.setText((String) tbPessoa.getValueAt(tbPessoa.getSelectedRow(), 0));
            txtSobrenome.setText((String) tbPessoa.getValueAt(tbPessoa.getSelectedRow(), 1));
            txtCod.setText((String) tbPessoa.getValueAt(tbPessoa.getSelectedRow(), 2));
            cbTipo.setSelectedItem(tbPessoa.getValueAt(tbPessoa.getSelectedRow(), 3));
            txtTelefone.setText((String) tbPessoa.getValueAt(tbPessoa.getSelectedRow(), 4));
            txtContato.setText((String) tbPessoa.getValueAt(tbPessoa.getSelectedRow(), 5));
            habilita();
            if (txtCod.getText().length() == 11) {
                rdFisica.setSelected(true);
                rdJuridica.setSelected(false);
            } else {
                rdJuridica.setSelected(true);
                rdFisica.setSelected(false);
            }

        }
    }//GEN-LAST:event_tbPessoaMouseClicked

    private void tbPessoaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbPessoaKeyReleased
        if (tbPessoa.getSelectedRow() != -1) {
            txtNome.setText((String) tbPessoa.getValueAt(tbPessoa.getSelectedRow(), 0));
            txtSobrenome.setText((String) tbPessoa.getValueAt(tbPessoa.getSelectedRow(), 1));
            txtCod.setText((String) tbPessoa.getValueAt(tbPessoa.getSelectedRow(), 2));
            cbTipo.setSelectedItem(tbPessoa.getValueAt(tbPessoa.getSelectedRow(), 3));
            txtTelefone.setText((String) tbPessoa.getValueAt(tbPessoa.getSelectedRow(), 4));
            txtContato.setText((String) tbPessoa.getValueAt(tbPessoa.getSelectedRow(), 5));
            habilita();
            if (txtCod.getText().length() == 11) {
                rdFisica.setSelected(true);
                rdJuridica.setSelected(false);
            } else {
                rdJuridica.setSelected(true);
                rdFisica.setSelected(false);
            }

        }
    }//GEN-LAST:event_tbPessoaKeyReleased

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed

    private void rdFisicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdFisicaMouseClicked

    }//GEN-LAST:event_rdFisicaMouseClicked

    private void rdJuridicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdJuridicaMouseClicked

    }//GEN-LAST:event_rdJuridicaMouseClicked

    private void carregaCb() {
        this.cbTipo.removeAllItems();
        this.cbTipo.addItem(TipoContato.EMAIL.getDescricao());
        this.cbTipo.addItem(TipoContato.FAX.getDescricao());
        this.cbTipo.addItem(TipoContato.SINAL_FUMACA.getDescricao());
        this.cbTipo.addItem(TipoContato.WHATSAPP.getDescricao());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btValidar;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbConflito;
    private javax.swing.JLabel lbContato;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSobrenome;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JRadioButton rdFisica;
    private javax.swing.JRadioButton rdJuridica;
    private javax.swing.JTable tbPessoa;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSobrenome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
